### ISSUE TITLE
I'm probably being an idiot but I can't install 3.0

### ISSUE THREAD

**Issue by Dostojetski** [scaredyfish/blender-rhubarb-lipsync#18]
I don't have the greatest confidence in my blender skills but I can't get the 3.0 version to install. I'm using blender 2.83 Alpha

When I select the addon to install, I get a splash that it installed but I cant find it in my addon list anywhere.

**Comment by scaredyfish** [comment]
This was my fault, I messed up the packaging process. Please download the latest release and it should work now.

**Comment by crackedeggs1** [comment]
Similar issue with 3.01 and Blender 2.83. No matter which packaged .py I select to install, Blender doesn't seem to do anything. The add-on install file chooser disappears, and my addon list still does not contain the addon.

It would be helpful to include install directions in the readme so we know we're not doing something wrong.

**Comment by crackedeggs1** [comment]
It turns out you shouldn't use the Addon Install option to install this. On Windows, you have to manually copy the ZIP directory into C:/Users/username/AppData/Roaming/Blender Foundation/Blender/28x/scripts/addons
Then it will be picked up by the add-on list, under the Community section.
You should manually delete any files from this add-on that you attempted to install a different way that appear in that directory, as their presence will cause the add-on list not to load (errors in the command line).

**Comment by scaredyfish** [comment]
@vaultwiki What zip file did you download? I've just re-tested on Windows and addon install is working for me.

**Comment by crackedeggs1** [comment]
Releases > 3.0.1. Extracted the contents. From the folder, selected __init__.py, also each of the other .py when that didn't work. If that's not the right way, that's why installation instructions should be posted/included.

**Comment by scaredyfish** [comment]
Thanks for the feedback. I will try to improve the documentation.
